# Generated by Django 5.1 on 2024-08-22 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conversions', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
            ],
        ),
    ]
